### ISSUE TITLE
SIdebar Blank

### ISSUE THREAD

**Issue by aliuq** [wong2/bing-sidebar-for-chrome#3]
![image](https://github.com/wong2/bing-chat-sidebar-for-chrome/assets/11707934/fc35098f-312d-47ec-84e6-3c68e4b8eb4e)

**Comment by wong2** [comment]
Can you try to close and open again?

**Comment by aliuq** [comment]
Tyied it, always blank

**Comment by wong2** [comment]
好的，可以把开发者工具切换到“元素”那里，看看iframe的src是什么嘛

**Comment by aliuq** [comment]
`https://edgeservices.bing.com/edgesvc/chat?udsframed=1&form=SHORUN&clientscopes=chat,noheader,channelstable,&shellsig=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&lightschemeovr=1`

**Comment by wong2** [comment]
🤔，看着挺正常的。你看看自己直接在 bing.com 能不能聊天呢？

**Comment by aliuq** [comment]
![image](https://github.com/wong2/bing-chat-sidebar-for-chrome/assets/11707934/d61f868e-7a6e-4cb1-8d38-167c899b5ea1)

edge 浏览器可以

**Comment by aliuq** [comment]
该不会是我自己得需要在 chrome 浏览器中能访问 bing 聊天吧？🤣

**Comment by wong2** [comment]
不是，这个插件做了处理，让你可以在Chrome里使用bing聊天。上面那样问的原因是想确认是否是侧边栏的问题。所以你现在在Chrome里直接打开bing.com，可以正常聊天嘛？

**Comment by aliuq** [comment]
之前 bing.com 是登录的状态，安装扩展后，一片黑白以为是账号登录的问题，退出登录后还是黑白，刚重新登录了微软账号，现在可以正常打开 bing 聊天了，现在侧边栏也可以打开了

**Comment by wong2** [comment]
好的好的

**Comment by aliuq** [comment]
再多问一句，我现在通过 bing.com 能直接打开 bing 聊天，也是扩展实现的吗？

**Comment by wong2** [comment]
对的，改了UA之类的

**Comment by aliuq** [comment]
赞赞赞
