### ISSUE TITLE
The feature to access to the content of current web page doesn't work

### ISSUE THREAD

**Issue by fuckseewoandcentern** [wong2/bing-sidebar-for-chrome#6]
I'm using Ungoogled Chromium with adguard enabled and third party cookie destruction enabled in adguard desktop.I'm not sure if the feature not working is a problem with the plugin itself or with my settings
<img width="1120" alt="屏幕截图 2023-07-16 102607" src="https://github.com/chathub-dev/bing-chat-sidebar-for-chrome/assets/81065949/061b7afe-ab4b-4d51-9ff6-58ce846beeed">

**Comment by wong2** [comment]
I believe this has some relation with your secure settings. Can you try with a normal Chrome browser?

**Comment by fuckseewoandcentern** [comment]
<img width="1120" alt="屏幕截图 2023-07-18 115910" src="https://github.com/chathub-dev/bing-chat-sidebar-for-chrome/assets/81065949/7f991e58-a1d1-4917-abd3-ef87172b604c">
Still doesn't work when I disable Adguard and use Goodle's Chrome

**Comment by wong2** [comment]
Please try with the latest version
