### ISSUE TITLE
Doesn't work at all in Arc browser

### ISSUE THREAD

**Issue by stevensyp** [wong2/bing-sidebar-for-chrome#7]
The extension doesn't work (nothing happens when clicking on the icon) in (chromium based) Arc browser. The setup process works fine, and I'm logged into Bing.

Arc Version 1.1.1 (40415)
Chromium Engine Version 115.0.5790.114

**Comment by wong2** [comment]
Yes, it's clearly stated in the README & Chrome web store description that it may not work in all Chromium-based browsers because of extension API compatibility.

https://github.com/chathub-dev/bing-chat-sidebar-for-chrome#supported-browsers

**Comment by samwzlim** [comment]
Any chance that this extension will be developed to work on Arc browswer?

**Comment by wong2** [comment]
There's nothing we can do about it. Arc doesn't have a `sidePanel` at all.
